import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Cookbook',
      items: [{type: 'autogenerated', dirName: 'cookbook'}],
    },
    {
      type: 'category',
      label: 'Sonix',
      items: [{type: 'autogenerated', dirName: 'sonix'}],
    },
    {
      type: 'category',
      label: 'Tona',
      items: [{type: 'autogenerated', dirName: 'tona'}],
    },
    {
      type: 'category',
      label: 'Tessera',
      items: [{type: 'autogenerated', dirName: 'tessera'}],
    },
    {
      type: 'category',
      label: 'Accura',
      items: [{type: 'autogenerated', dirName: 'accura'}],
    },
    {
      type: 'category',
      label: 'Calibra',
      items: [{type: 'autogenerated', dirName: 'calibra'}],
    },
    {
      type: 'category',
      label: 'Common',
      items: [{type: 'autogenerated', dirName: 'common'}],
    },
  ],
  // API Reference uses Dokka HTML (separate from Docusaurus)
  // Access via /api/index.html
};

export default sidebars;
